version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.12.2
    ports:
      - 9200:9200
    volumes:
      - "./es/data:/usr/share/elasticsearch/data"
      - "./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green"]
      retries: 300
      interval: 2s

  kibana:
    image: kibana:8.12.2
    ports:
      - 5601:5601
    depends_on: [ "elasticsearch" ]
    volumes:
      - "./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      retries: 300
      interval: 2s