version: "3.9"

services:
  db:
    container_name: "db"
    build: ./services/db
    env_file:
      - ./services/backend/.env
    volumes:
      - ./services/db/data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - 5433:5432
    healthcheck:
        test: ["CMD", "psql", "-h", "localhost", "-U", "app", "-d", "movies_database"]
        interval: 2s
        retries: 100

  sqlite-transfer:
    container_name: "sqlite-transfer"
    build: ./services/sqlite_transfer
    env_file:
      - ./services/backend/.env
    depends_on:
      app:
        condition: service_healthy

  app:
    container_name: "app"
    build: ./services/backend
    env_file:
      - ./services/backend/.env
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./services/backend/static:/opt/app/static
    healthcheck:
      test: ["CMD-SHELL", "[ -e /opt/app/static ]"]
      interval: 2s
      retries: 100

  swagger:
    container_name: "docs"
    image: swaggerapi/swagger-ui:v5.11.8
    volumes:
      - ./services/swagger/openapi.yaml:/swagger.yaml
    env_file:
      - ./services/backend/.env
    ports:
      - 8080:8080
    depends_on:
      - app

  nginx:
    container_name: "nginx"
    restart: always
    build: ./services/nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/configs:/etc/nginx/conf.d:ro
      - ./services/backend/static:/static/:ro
    depends_on:
      - app
    ports:
      - "80:80"

  elasticsearch:
    container_name: "elasticsearch"
    image: elasticsearch:8.12.1
    ports:
      - 9200:9200
    volumes:
      - "./services/es/data:/usr/share/elasticsearch/data"
      - "./services/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green"]
      retries: 300
      interval: 2s

  kibana:
    container_name: "kibana"
    image: kibana:8.12.1
    ports:
      - 5601:5601
    depends_on: [ "elasticsearch" ]
    volumes:
      - "./services/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      retries: 300
      interval: 2s